---
global-variables:
  acp-docker-image: &acp-docker-image 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest

kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64


environment:
  TERRAFORM_VERSION: 1.5.7
  TERRAGRUNT_VERSION: 0.52.7

steps:
- name: build_docker_image
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - /usr/local/bin/wait
    - docker build --build-arg TERRAFORM_VERSION=$${TERRAFORM_VERSION} --build-arg TERRAGRUNT_VERSION=$${TERRAGRUNT_VERSION} --tag dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER} .
  when:
    event:
    - push

- name: push_image_to_quay
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - docker login --username=$${DOCKER_USERNAME} --password=$${DOCKER_PASSWORD} quay.io
    - docker tag dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER}
  when:
    branch:
      exclude:
        - master
    event:
      - push


- name: push_master_image_to_quay
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - docker login --username=$${DOCKER_USERNAME} --password=$${DOCKER_PASSWORD} quay.io
    - docker tag dq-docker-terragrunt:b-${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/dq-docker-terragrunt:v$${TERRAGRUNT_VERSION}
    - docker push quay.io/ukhomeofficedigital/dq-docker-terragrunt:v$${TERRAGRUNT_VERSION}
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
      - master
    event:
    - push

- name: trivy_scan_master
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-docker-terragrunt:v$${TERRAGRUNT_VERSION}
  when:
    branch:
        - master
    event:
      - push


services:
- name: docker
  image: *acp-docker-image
